# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' listKeys -- Print out information for all secret keys
#' @example getKeys()
listKeys <- function() {
    invisible(.Call('rgpg_listKeys', PACKAGE = 'rgpg'))
}

